### ISSUE TITLE
pip install -e and console scripts 

### ISSUE THREAD

**Issue by Permafacture** [python-viper/viper#11]
Two important use cases that virtualenvs preserve are `pip install -e` and the console_scripts entry point in setup.py. Both of these very naturally lend themselves to cd'ing around: opening interpreters and executing command line arguments.

`pip install -e` exists because you don't want to have to stay frozen in one directory.  You might have data spread across many directories and you don't want to type long paths or create symbolic links.  I often download data from servers into the /tmp/ directory so I don't have to worry about remembering to delete it.

The console_script entry point is what let's you install a package and get an executable command line program.  For instance, I am working on a file parser and I provide the parse_file entry point.  Then from the bash shell I can run `parse_file input.obj deleteme.png`.  I don't want to install this fun little utility globally with sudo yet, not even in editable mode. Or I might have the released copy and my dev version both available.

Maybe you could have a viper-with command that puts you in a virtual environment described by whatever config file you give it.  But then I'd use that all the time and it would be similar virtualenv-wrapper or conda or what have you except you still have to specify a path to the environment config.

**Comment by daegontaven** [comment]
I don't want to discard that you have valid points. First `pip install -e` is kind of like a wrapper over setuptools develop function. Also you would not lose console_scripts or anything setuptools has to offer. This will most likely be a wrapper around pip and setuptools. Nothing is lost. I would suggest you read up some documentation on setuptools and about the import system of python. Also take a look at the [site]( https://docs.python.org/3/library/site.html ) module that does most of this for us.

**Comment by Permafacture** [comment]
I understand that those functionalities would technically still exist. It's
just that the common use case that they address is not addressed. I think
the console script is the most clear example.

**Comment by daegontaven** [comment]
I still don't think you understand that viper is wrapping over setuptools. Setuptools is what's mainly responsible for console_scripts. This is something that would taken up with advice from PyPa if it's decided to be implemented. We understand you are worried. We don't plan on breaking compatibility with existing packages. Please read up on setuptools before raising another issue. Thank you for your concerns.
